### ISSUE TITLE
MVP Timeline & Schema

### ISSUE THREAD

**Issue by andrewlangston** [hsteg/HarryHood#1]
Harrison,

Good job setting up your fullstack project repo! Moving forward, we will be using Github issues to track outstanding points to addressed (alongside Slack, etc.). Please see below for a few notes regarding your preliminary design documents:

- [x] Given that `watchlists` is a joins table, I would suggest naming it something more semantic like `watches` or `user_watches`.
- [x] How will you handle stock sales?
- [x] Asset data can be fetched through an external API, so we can trim down the `stocks` table significantly. You should only need columns for `name` and `symbol`. Take a look [here](https://iextrading.com/) for more info.

Let me know if you have any questions!

**Comment by hsteg** [comment]
Also, I'm considering adding some functionality to my app -- namely dividend payouts and tags (Apple would have tags of "technology", "consumer electronics", "computer hardware", etc).  Both of those things are available in the API.  Is this something I should add now, or consider bonus functionality once I have my current scope up and running?

**Comment by andrewlangston** [comment]
Harrison,

I like the idea of using a boolean to represent stock sales/buys. Please do mark the checkboxes as you address points within the issue, and comment when you are finished. I'll then do one more review and close the issue if everything looks good. You're always welcome to reach out via Slack with questions!

With respect to added functionality: I would hold off on this for now. Better saved for bonus features if time permits.
